// code/Angular/democomptest_a/src/app/app.component.ts
import { Component } from '@angular/core';
import 'ba-democomponents';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'democomptest_a';
}

<my-mover></my-mover>
<my-propbinding input="Text from property"></my-propbinding>
<my-event-emitter></my-event-emitter>
<my-event-listener></my-event-listener>

// code/react/democomptest_r/src/App.js
import logo from './logo.svg';
import './App.css';

function App() {
  return (
    <div className="App">
      <my-mover></my-mover>
      <my-propbinding input="Text from property"></my-propbinding>
      <my-event-emitter></my-event-emitter>
      <my-event-listener></my-event-listener>
    </div>
  );
}

export default App;
